# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
     spool: { type: 'memory' }
     transport: gmail
     username: malek.raissi9@gmail.com
     password: malekraissi123
     host: smtp.gmail.com
     port: 465
     encryption: tls
     disable_delivery: false












