easy_admin:
  design:
    menu:
      - label: 'Utilisateur'
        icon: 'newspaper-o'
        children:
          - {entity: 'Utilisateur', icon: 'plus', label: 'Création des utilisateurs', params: {action: 'new'} }
          - {entity: 'Utilisateur', icon: 'th-list', label: 'liste des utilisateurs'}
      - label: 'contrat'
        icon: 'newspaper-o'
        children:
          - {entity: 'Contrat', icon: 'th-list', label: 'liste des Contrats'}
      - label: 'Pole'
        icon: 'newspaper-o'
        children:
          - {entity: 'Pole', icon: 'th-list', label: 'liste des poles'}

      - label: 'Equipe'
        icon: 'newspaper-o'
        children:
          - {entity: 'Equipe', icon: 'th-list', label: 'liste des equipes'}


      - label: 'Client'
        icon: 'newspaper-o'
        children:
          - {entity: 'Client', icon: 'th-list', label: 'liste des clients'}






