easy_admin:
  entities:
    Client:
      class: App\Entity\Client
      list:
        fields:
          - { property: 'nom' , type: 'string',label: 'nom' }
          - { property: 'adresse' , type: 'string',label: 'adresse' }
          - { property: 'email' , type: 'string',label: 'email' }
          - { property: 'tel' , type: 'string',label: 'tel' }
        actions: