easy_admin:
  entities:
    Pole:
      class: App\Entity\Pole
      form:
        fields:
          - 'nom'
      list:
        fields:
          - { property: 'nom' , type: 'string',label: 'nom' }

        actions: