easy_admin:
  entities:
    Utilisateur:


      class: App\Entity\Utilisateur


      form:
        fields:
          - { type: 'section', label: 'Etat civil' }
          - 'prenom'
          - 'nom'
          - 'civilite'
          - 'situation_familiale'
          - { type: 'section', label: 'coordonnées'}
          - 'adresse'
          - 'code_postal'
          - 'tel1'
          - 'tel2'
          - 'email'
          - 'mail_pro'
          - 'rip'
          - { type: 'section', label: 'compétences'}
          - 'universite'
          - 'diplome'
          - 'specialite'
          - 'annee_obtination'
          - 'langage'
          - { type: 'section', label: 'immatriculation'}
          - 'date_naiss'
          - 'lieu'
          - 'cin'
          - 'date_cin'
          - 'nationalite'
          - 'num_cnss'
          - { type: 'section', label: 'contrat'}
          - 'contrat'
          - { type: 'section', label: 'equipes'}
          - 'equipes'




      #templates:
        #new: 'Utilisateur/edit.html.twig'

      list :
        fields:
          - { property: 'matricule' , type: 'string',label: 'matricule' }
          - { property: 'prenom' , type: 'string',label: 'prenom' }
          - { property: 'nom' , type: 'string',label: 'nom' }
          - { property: 'email' , type: 'string',label: 'email' }
          - { property: 'tel1' , type: 'string',label: 'téléphone' }
          - { property: 'nullable = truecontrat' , type: 'string',label: 'contrat' }
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-success '}
          - {name: 'new',  label: 'ajouter'}
          - {name: 'show', icon: 'tag', label: false, css_class: 'btn  btn-info' , background-color: '#FF358B' }
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger',style: ' background-color: #0dbb79;'}






